/*

 LEVEL_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\preco\Documents\robot_quest\res\level_map_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level_mapWidth 20
#define level_mapHeight 18
#define level_mapBank 0

extern unsigned char level_map[];

/* End of LEVEL_MAP.H */
